# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abdc7d4c3d113a32eea0abae9c8138638c933a02bd542b464dd32d3d4e27ad156b9fb2b47ab9225a890e889f72f0f50d585fd0e5f4eb142cee5ae2c40e1bc4b6

test:
  secret_key_base: db320a055b9a2c6b31977ce71aeaed47fe117821c3cb91dc419c870ca3fb90832c708173628a4eff9c91325f16c9f424a18b5231c20deaa2d26de752575be69d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
